const hospitalData = [
    { name: "Indraprastha Apollo Hospital", location: "New Delhi, Delhi", stock: { "A+": 25, "O-": 10, "B+": 30 }, status: "active", theme: "good" },
    { name: "Fortis Memorial Research Institute", location: "Gurugram, Haryana", stock: { "O+": 40, "A-": 12, "AB+": 15 }, status: "active", theme: "good" },
    { name: "Sir Ganga Ram Hospital", location: "Rajinder Nagar, New Delhi", stock: { "B+": 18, "O-": 5, "A+": 22 }, status: "busy", theme: "warning" },
    { name: "AIIMS Delhi", location: "Ansari Nagar, New Delhi", stock: { "O-": 2, "A+": 45, "B-": 8 }, status: "busy", theme: "critical" },
    { name: "Max Super Speciality Hospital", location: "Saket, New Delhi", stock: { "AB-": 5, "O+": 35, "A-": 14 }, status: "active", theme: "good" },
    { name: "Medanta - The Medicity", location: "Gurugram, Haryana", stock: { "B+": 50, "O+": 60, "A+": 40 }, status: "active", theme: "good" },
    { name: "Tata Memorial Hospital", location: "Parel, Mumbai", stock: { "O-": 15, "A+": 20, "B+": 25 }, status: "active", theme: "good" },
    { name: "Kokilaben Dhirubhai Ambani Hospital", location: "Andheri West, Mumbai", stock: { "A-": 8, "O+": 30, "AB+": 12 }, status: "active", theme: "good" },
    { name: "P.D. Hinduja National Hospital", location: "Mahim, Mumbai", stock: { "B-": 10, "A+": 18, "O-": 4 }, status: "busy", theme: "warning" },
    { name: "Nanavati Max Super Speciality Hospital", location: "Vile Parle, Mumbai", stock: { "O+": 25, "B+": 20, "A-": 6 }, status: "active", theme: "good" },
    { name: "Jaslok Hospital", location: "Pedder Road, Mumbai", stock: { "AB+": 10, "O-": 7, "A+": 15 }, status: "active", theme: "good" },
    { name: "Sir H. N. Reliance Foundation Hospital", location: "Girgaon, Mumbai", stock: { "B+": 22, "A+": 30, "O+": 45 }, status: "active", theme: "good" },
    { name: "Lilavati Hospital & Research Centre", location: "Bandra West, Mumbai", stock: { "O-": 3, "B-": 5, "A+": 12 }, status: "busy", theme: "critical" },
    { name: "Manipal Hospital", location: "Old Airport Road, Bengaluru", stock: { "A+": 35, "O+": 50, "B+": 40 }, status: "active", theme: "good" },
    { name: "Aster CMI Hospital", location: "Hebbal, Bengaluru", stock: { "O-": 8, "AB-": 4, "A-": 10 }, status: "active", theme: "good" },
    { name: "Narayana Health City", location: "Bommasandra, Bengaluru", stock: { "B+": 45, "O+": 55, "A+": 38 }, status: "active", theme: "good" },
    { name: "St. John's Medical College Hospital", location: "Koramangala, Bengaluru", stock: { "O-": 12, "A+": 25, "B+": 20 }, status: "active", theme: "good" },
    { name: "Apollo Hospital Greams Road", location: "Chennai, Tamil Nadu", stock: { "A+": 40, "O-": 15, "B+": 35 }, status: "active", theme: "good" },
    { name: "Christian Medical College (CMC)", location: "Vellore, Tamil Nadu", stock: { "O+": 100, "A+": 80, "B+": 90 }, status: "active", theme: "good" },
    { name: "Fortis Malar Hospital", location: "Adyar, Chennai", stock: { "AB+": 12, "O-": 6, "A-": 9 }, status: "busy", theme: "warning" },
    { name: "MIOT International", location: "Manapakkam, Chennai", stock: { "B-": 15, "O+": 40, "A+": 25 }, status: "active", theme: "good" },
    { name: "Apollo Health City", location: "Jubilee Hills, Hyderabad", stock: { "A+": 30, "O-": 10, "B+": 25 }, status: "active", theme: "good" },
    { name: "Yashoda Hospitals", location: "Secunderabad, Hyderabad", stock: { "O+": 35, "A-": 8, "AB+": 14 }, status: "active", theme: "good" },
    { name: "Care Hospitals", location: "Banjara Hills, Hyderabad", stock: { "B+": 20, "O-": 5, "A+": 15 }, status: "busy", theme: "warning" },
    { name: "KIMS Hospitals", location: "Secunderabad, Hyderabad", stock: { "O-": 4, "A+": 20, "B-": 7 }, status: "active", theme: "good" },
    { name: "Nizam's Institute of Medical Sciences", location: "Punjagutta, Hyderabad", stock: { "A+": 22, "O+": 30, "B+": 28 }, status: "active", theme: "good" },
    { name: "AMRI Hospitals", location: "Dhakuria, Kolkata", stock: { "O-": 6, "A-": 8, "B+": 12 }, status: "active", theme: "good" },
    { name: "Apollo Multispeciality Hospitals", location: "Canal Circular Road, Kolkata", stock: { "A+": 25, "O+": 35, "B+": 30 }, status: "active", theme: "good" },
    { name: "Ruby General Hospital", location: "Kasba, Kolkata", stock: { "AB-": 3, "O-": 5, "A+": 10 }, status: "busy", theme: "warning" },
    { name: "Fortis Hospital Anandapur", location: "Kolkata, West Bengal", stock: { "O+": 20, "B+": 15, "A-": 7 }, status: "active", theme: "good" },
    { name: "Jehangir Hospital", location: "Sassoon Road, Pune", stock: { "A+": 18, "O-": 5, "B+": 22 }, status: "active", theme: "good" },
    { name: "Sahyadri Super Speciality Hospital", location: "Deccan Gymkhana, Pune", stock: { "O+": 25, "A-": 6, "AB+": 10 }, status: "active", theme: "good" },
    { name: "Ruby Hall Clinic", location: "Sassoon Road, Pune", stock: { "B-": 8, "A+": 20, "O-": 4 }, status: "busy", theme: "warning" },
    { name: "CIMS Hospital", location: "Sola, Ahmedabad", stock: { "A+": 22, "O+": 30, "B+": 25 }, status: "active", theme: "good" },
    { name: "Zydus Hospital", location: "Thaltej, Ahmedabad", stock: { "O-": 10, "A-": 5, "AB+": 8 }, status: "active", theme: "good" },
    { name: "Apollo Hospitals International City", location: "Ahmedabad, Gujarat", stock: { "B+": 15, "O+": 20, "A+": 18 }, status: "active", theme: "good" },
    { name: "Fortis Escorts Heart Institute", location: "Okhla, New Delhi", stock: { "A+": 12, "O-": 3, "B+": 10 }, status: "busy", theme: "critical" },
    { name: "Blk-Max Super Speciality Hospital", location: "Pusa Road, New Delhi", stock: { "O+": 28, "A-": 7, "AB+": 11 }, status: "active", theme: "good" },
    { name: "Moolchand Hospital", location: "Lajpat Nagar, New Delhi", stock: { "B+": 20, "O-": 8, "A+": 15 }, status: "active", theme: "good" },
    { name: "Holy Family Hospital", location: "Okhla, New Delhi", stock: { "O+": 25, "A+": 22, "B+": 18 }, status: "active", theme: "good" },
    { name: "Batra Hospital & Medical Research Centre", location: "Tughlakabad, New Delhi", stock: { "A-": 5, "O-": 4, "B-": 6 }, status: "busy", theme: "warning" },
    { name: "Fortis Hospital Mohali", location: "Mohali, Punjab", stock: { "A+": 15, "O+": 20, "B+": 18 }, status: "active", theme: "good" },
    { name: "PGIMER", location: "Chandigarh", stock: { "O-": 12, "A+": 40, "B+": 35 }, status: "active", theme: "good" },
    { name: "Government Medical College and Hospital", location: "Sector 32, Chandigarh", stock: { "B+": 25, "O+": 30, "A-": 10 }, status: "active", theme: "good" },
    { name: "Aster Medcity", location: "Kochi, Kerala", stock: { "A+": 20, "O-": 8, "B+": 15 }, status: "active", theme: "good" },
    { name: "Amrita Hospital", location: "Edappally, Kochi", stock: { "O+": 45, "A-": 12, "AB+": 18 }, status: "active", theme: "good" },
    { name: "Rajagiri Hospital", location: "Aluva, Kochi", stock: { "B+": 22, "O-": 5, "A+": 15 }, status: "busy", theme: "warning" },
    { name: "Lakeshore Hospital", location: "Nettoor, Kochi", stock: { "A+": 18, "O+": 25, "B-": 7 }, status: "active", theme: "good" },
    { name: "Sree Chitra Tirunal Institute", location: "Thiruvananthapuram, Kerala", stock: { "O-": 4, "A+": 15, "B+": 12 }, status: "active", theme: "good" },
    { name: "KIMSHEALTH", location: "Thiruvananthapuram, Kerala", stock: { "A-": 6, "O+": 22, "AB+": 9 }, status: "active", theme: "good" },
    { name: "Baby Memorial Hospital", location: "Kozhikode, Kerala", stock: { "B+": 18, "O-": 6, "A+": 14 }, status: "active", theme: "good" },
    { name: "Meitra Hospital", location: "Kozhikode, Kerala", stock: { "O+": 20, "A-": 5, "B+": 15 }, status: "active", theme: "good" },
    { name: "Aster MIMS", location: "Kozhikode, Kerala", stock: { "A+": 25, "O-": 10, "B+": 20 }, status: "active", theme: "good" },
    { name: "Apollo BGS Hospitals", location: "Mysuru, Karnataka", stock: { "O+": 15, "A-": 4, "AB+": 7 }, status: "busy", theme: "warning" },
    { name: "JSS Hospital", location: "Mysuru, Karnataka", stock: { "B+": 22, "O-": 8, "A+": 18 }, status: "active", theme: "good" },
    { name: "Columbia Asia Hospital", location: "Mysuru, Karnataka", stock: { "A+": 12, "O+": 18, "B-": 5 }, status: "active", theme: "good" },
    { name: "Kasturba Hospital", location: "Manipal, Karnataka", stock: { "O-": 15, "A+": 35, "B+": 30 }, status: "active", theme: "good" },
    { name: "Father Muller Medical College Hospital", location: "Mangaluru, Karnataka", stock: { "A+": 20, "O+": 25, "B+": 22 }, status: "active", theme: "good" },
    { name: "A.J. Hospital & Research Centre", location: "Mangaluru, Karnataka", stock: { "O-": 6, "A-": 8, "AB+": 10 }, status: "active", theme: "good" },
    { name: "KMC Hospital", location: "Mangaluru, Karnataka", stock: { "B+": 18, "O+": 22, "A+": 20 }, status: "active", theme: "good" },
    { name: "Continental Hospitals", location: "Gachibowli, Hyderabad", stock: { "A+": 15, "O-": 4, "B+": 12 }, status: "busy", theme: "warning" },
    { name: "Star Hospitals", location: "Banjara Hills, Hyderabad", stock: { "O+": 28, "A-": 6, "AB+": 11 }, status: "active", theme: "good" },
    { name: "Sunshine Hospitals", location: "Secunderabad, Hyderabad", stock: { "B+": 18, "O-": 5, "A+": 14 }, status: "active", theme: "good" },
    { name: "Virinchi Hospitals", location: "Banjara Hills, Hyderabad", stock: { "A+": 12, "O+": 20, "B-": 4 }, status: "active", theme: "good" },
    { name: "Rainbow Children's Hospital", location: "Banjara Hills, Hyderabad", stock: { "O-": 8, "A-": 5, "B+": 15 }, status: "active", theme: "good" },
    { name: "Fortis Hospital Mulund", location: "Mumbai, Maharashtra", stock: { "A+": 22, "O+": 35, "B+": 28 }, status: "active", theme: "good" },
    { name: "Global Hospitals", location: "Parel, Mumbai", stock: { "O-": 10, "A-": 8, "AB+": 15 }, status: "active", theme: "good" },
    { name: "Wockhardt Hospital", location: "Mumbai Central, Mumbai", stock: { "B+": 20, "O-": 6, "A+": 18 }, status: "active", theme: "good" },
    { name: "S. L. Raheja Hospital", location: "Mahim, Mumbai", stock: { "A+": 15, "O+": 22, "B-": 5 }, status: "busy", theme: "warning" },
    { name: "SevenHills Hospital", location: "Andheri East, Mumbai", stock: { "O-": 12, "A+": 30, "B+": 25 }, status: "active", theme: "good" },
    { name: "Jupiter Hospital", location: "Thane, Maharashtra", stock: { "A+": 20, "O+": 28, "B+": 22 }, status: "active", theme: "good" },
    { name: "Hiranandani Hospital", location: "Powai, Mumbai", stock: { "O-": 5, "A-": 4, "AB+": 8 }, status: "busy", theme: "critical" },
    { name: "Bhaktivedanta Hospital", location: "Mira Road, Mumbai", stock: { "B+": 15, "O+": 20, "A+": 18 }, status: "active", theme: "good" },
    { name: "Fortis Hospital Kalyan", location: "Kalyan, Maharashtra", stock: { "A+": 12, "O-": 3, "B+": 10 }, status: "busy", theme: "warning" },
    { name: "Deenanath Mangeshkar Hospital", location: "Erandwane, Pune", stock: { "O+": 40, "A+": 35, "B+": 38 }, status: "active", theme: "good" },
    { name: "Inlaks & Budhrani Hospital", location: "Koregaon Park, Pune", stock: { "O-": 8, "A-": 6, "AB+": 12 }, status: "active", theme: "good" },
    { name: "Nobel Hospital", location: "Hadapsar, Pune", stock: { "B+": 22, "O-": 7, "A+": 18 }, status: "active", theme: "good" },
    { name: "Aditya Birla Memorial Hospital", location: "Chinchwad, Pune", stock: { "A+": 25, "O+": 30, "B+": 28 }, status: "active", theme: "good" },
    { name: "Sancheti Hospital", location: "Shivajinagar, Pune", stock: { "O-": 5, "A-": 4, "B-": 6 }, status: "busy", theme: "warning" },
    { name: "Poona Hospital & Research Centre", location: "Sadashiv Peth, Pune", stock: { "B+": 15, "O+": 20, "A+": 18 }, status: "active", theme: "good" },
    { name: "Columbia Asia Hospital", location: "Kharadi, Pune", stock: { "A+": 10, "O-": 2, "B+": 12 }, status: "busy", theme: "critical" },
    { name: "Sterling Hospital", location: "Memnagar, Ahmedabad", stock: { "O+": 25, "A-": 7, "AB+": 10 }, status: "active", theme: "good" },
    { name: "Shelby Hospital", location: "Prahlad Nagar, Ahmedabad", stock: { "B+": 20, "O-": 6, "A+": 18 }, status: "active", theme: "good" },
    { name: "KD Hospital", location: "Vaishno Devi Circle, Ahmedabad", stock: { "A+": 15, "O+": 22, "B-": 5 }, status: "active", theme: "good" },
    { name: "HCG Cancer Centre", location: "Sola, Ahmedabad", stock: { "O-": 10, "A-": 8, "AB+": 12 }, status: "active", theme: "good" },
    { name: "Sola Civil Hospital", location: "Sola, Ahmedabad", stock: { "B+": 30, "O+": 40, "A+": 35 }, status: "active", theme: "good" },
    { name: "Ahmedabad Civil Hospital", location: "Asarwa, Ahmedabad", stock: { "O-": 20, "A+": 60, "B+": 55 }, status: "active", theme: "good" },
    { name: "SMS Hospital", location: "Jaipur, Rajasthan", stock: { "A+": 45, "O+": 70, "B+": 65 }, status: "active", theme: "good" },
    { name: "Fortis Escorts Hospital", location: "Malviya Nagar, Jaipur", stock: { "O-": 12, "A-": 8, "AB+": 15 }, status: "active", theme: "good" },
    { name: "Eternal Hospital", location: "Malviya Nagar, Jaipur", stock: { "B+": 25, "O-": 10, "A+": 22 }, status: "active", theme: "good" },
    { name: "Narayana Multispeciality Hospital", location: "Pratap Nagar, Jaipur", stock: { "A+": 20, "O+": 28, "B+": 25 }, status: "active", theme: "good" },
    { name: "Manipal Hospital", location: "Vidhyadhar Nagar, Jaipur", stock: { "O-": 8, "A-": 6, "B-": 10 }, status: "busy", theme: "warning" },
    { name: "Santokba Durlabhji Memorial Hospital", location: "Bhavani Singh Lame, Jaipur", stock: { "B+": 30, "O+": 40, "A+": 35 }, status: "active", theme: "good" },
    { name: "Jawahar Lal Nehru Hospital", location: "Ajmer, Rajasthan", stock: { "O-": 5, "A+": 20, "B+": 18 }, status: "active", theme: "good" },
    { name: "AIIMS Jodhpur", location: "Jodhpur, Rajasthan", stock: { "A+": 30, "O+": 45, "B+": 40 }, status: "active", theme: "good" },
    { name: "Goyal Hospital", location: "Jodhpur, Rajasthan", stock: { "O-": 4, "A-": 3, "AB+": 6 }, status: "busy", theme: "critical" },
    { name: "Mathura Das Mathur Hospital", location: "Jodhpur, Rajasthan", stock: { "B+": 22, "O+": 30, "A+": 25 }, status: "active", theme: "good" },
    { name: "Medanta Lucknow", location: "Sushant Golf City, Lucknow", stock: { "A+": 25, "O-": 10, "B+": 30 }, status: "active", theme: "good" },
    { name: "Sanjay Gandhi Post Graduate Institute", location: "Raibareli Road, Lucknow", stock: { "O+": 55, "A+": 45, "B+": 50 }, status: "active", theme: "good" },
    { name: "King George's Medical University", location: "Chowk, Lucknow", stock: { "O-": 15, "A-": 10, "B-": 12 }, status: "active", theme: "good" },
    { name: "Apollo Medics Super Speciality Hospital", location: "Lucknow, Uttar Pradesh", stock: { "A+": 20, "O+": 28, "B+": 25 }, status: "active", theme: "good" },
    { name: "Sahara Hospital", location: "Gomti Nagar, Lucknow", stock: { "O-": 8, "A-": 6, "AB+": 11 }, status: "busy", theme: "warning" },
    { name: "Ram Manohar Lohia Institute", location: "Vibhuti Khand, Lucknow", stock: { "B+": 35, "O+": 45, "A+": 40 }, status: "active", theme: "good" },
    { name: "Vivekananda Polyclinic", location: "Nirala Nagar, Lucknow", stock: { "A+": 15, "O-": 5, "B+": 18 }, status: "active", theme: "good" },
    { name: "AIIMS Bhopal", location: "Saket Nagar, Bhopal", stock: { "O+": 40, "A+": 35, "B+": 38 }, status: "active", theme: "good" },
    { name: "Hamidia Hospital", location: "Bhopal, Madhya Pradesh", stock: { "O-": 10, "A-": 8, "AB+": 12 }, status: "active", theme: "good" },
    { name: "Bansal Hospital", location: "Shahpura, Bhopal", stock: { "B+": 20, "O-": 6, "A+": 18 }, status: "active", theme: "good" },
    { name: "Chirayu Health & Medicare", location: "Bhopal, Madhya Pradesh", stock: { "A+": 25, "O+": 32, "B+": 30 }, status: "active", theme: "good" },
    { name: "Siddhanta Red Cross Hospital", location: "Bhopal, Madhya Pradesh", stock: { "O-": 5, "A-": 4, "B-": 7 }, status: "busy", theme: "warning" },
    { name: "Bombay Hospital Indore", location: "Vijay Nagar, Indore", stock: { "A+": 22, "O+": 30, "B+": 25 }, status: "active", theme: "good" },
    { name: "Choithram Hospital", location: "Manikbagh, Indore", stock: { "O-": 12, "A-": 8, "AB+": 15 }, status: "active", theme: "good" },
    { name: "Medanta Super Speciality Hospital", location: "Vijay Nagar, Indore", stock: { "B+": 28, "O-": 12, "A+": 24 }, status: "active", theme: "good" },
    { name: "Index Medical College Hospital", location: "Indore, Madhya Pradesh", stock: { "O+": 35, "A+": 30, "B+": 32 }, status: "active", theme: "good" },
    { name: "Apollo Hospitals Indore", location: "Indore, Madhya Pradesh", stock: { "A+": 18, "O-": 6, "B+": 20 }, status: "active", theme: "good" },
    { name: "CHL Hospital", location: "Indore, Madhya Pradesh", stock: { "O-": 4, "A-": 3, "B-": 5 }, status: "busy", theme: "critical" },
    { name: "AIIMS Bhubaneswar", location: "Bhubaneswar, Odisha", stock: { "A+": 35, "O+": 50, "B+": 45 }, status: "active", theme: "good" },
    { name: "SUM Hospital", location: "Bhubaneswar, Odisha", stock: { "O-": 15, "A-": 10, "AB+": 18 }, status: "active", theme: "good" },
    { name: "Kalinga Hospital", location: "Chandrasekharpur, Bhubaneswar", stock: { "B+": 25, "O-": 8, "A+": 22 }, status: "active", theme: "good" },
    { name: "Care Hospitals Bhubaneswar", location: "Prachi Enclave, Bhubaneswar", stock: { "A+": 20, "O+": 28, "B+": 24 }, status: "active", theme: "good" },
    { name: "Apollo Hospitals Bhubaneswar", location: "Bhubaneswar, Odisha", stock: { "O-": 10, "A-": 7, "B-": 9 }, status: "busy", theme: "warning" },
    { name: "AMRI Hospitals Bhubaneswar", location: "Bhubaneswar, Odisha", stock: { "B+": 18, "O+": 25, "A+": 20 }, status: "active", theme: "good" },
    { name: "SCB Medical College", location: "Cuttack, Odisha", stock: { "O-": 25, "A+": 70, "B+": 65 }, status: "active", theme: "good" },
    { name: "Jaypee Hospital", location: "Noida, Uttar Pradesh", stock: { "A+": 28, "O-": 12, "B+": 32 }, status: "active", theme: "good" },
    { name: "Fortis Hospital Noida", location: "Sector 62, Noida", stock: { "O+": 45, "A-": 15, "AB+": 20 }, status: "active", theme: "good" },
    { name: "Max Super Speciality Hospital", location: "Sector 19, Noida", stock: { "B+": 22, "O-": 8, "A+": 20 }, status: "busy", theme: "warning" },
    { name: "Apollo Hospitals Noida", location: "Sector 26, Noida", stock: { "O-": 6, "A-": 5, "B-": 8 }, status: "active", theme: "good" },
    { name: "Kailash Hospital", location: "Sector 27, Noida", stock: { "A+": 25, "O+": 35, "B+": 30 }, status: "active", theme: "good" },
    { name: "Metro Hospital", location: "Sector 11, Noida", stock: { "O-": 4, "A+": 15, "B+": 12 }, status: "busy", theme: "critical" },
    { name: "Sharda Hospital", location: "Greater Noida, Uttar Pradesh", stock: { "B+": 30, "O+": 40, "A+": 35 }, status: "active", theme: "good" },
    { name: "Fortis Escorts Hospital", location: "Neelam Railway Road, Faridabad", stock: { "A+": 15, "O-": 5, "B+": 18 }, status: "active", theme: "good" },
    { name: "Asian Institute of Medical Sciences", location: "Sector 21A, Faridabad", stock: { "O+": 28, "A-": 10, "AB+": 15 }, status: "active", theme: "good" },
    { name: "Sarvodaya Hospital", location: "Sector 8, Faridabad", stock: { "B+": 20, "O-": 6, "A+": 18 }, status: "active", theme: "good" },
    { name: "Metro Hospital Faridabad", location: "Sector 16, Faridabad", stock: { "A+": 12, "O+": 20, "B-": 5 }, status: "busy", theme: "warning" }
];
